title: Max Hoff
description: > # this means to ignore newlines until "baseurl:"
  Hey! I'm a Chicago-based analytics professional at JPMorgan Chase with a passion for over-analyzing everything. Currently pursuing a Master's in Information and Data Science at UC Berkeley. Take a look at some of the projects I've worked on in my free time!
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://maxwell-hoff.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: "https://twitter.com/rhiannon_io" #if your site has a twitter account, enter it here

# Author Settings
author: Max Hoff # add your name
author-img: maxhoff_headshot_skiing.PNG # add your photo
about-author: Hey! I'm a Chicago-based analytics professional at JPMorgan Chase with a passion for over-analyzing everything. Currently pursuing a Master's in Information and Data Science at UC Berkeley. Take a look at some of the projects I've worked on in my free time!
social-twitter: rhiannon_io # add your Twitter handle
social-facebook: max.hoff.313 add your Facebook handle
social-github: maxwell-hoff # ig handle
social-linkedin: max-hoff-47645771 # add your Linkedin handle
social-email: maxwell.hoff@berkeley.edu # add your Email address

# Disqus
discus-identifier: Max Hoff # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
